# config.yaml
symbol: "SPY"
frequency: 5
frequency_type: "minute"
model_type: "tft"

paths:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  scaler_dir: "data/processed/scalers"  
  model_dir: "models/"